apiVersion: karpenter.sh/v1alpha1
kind: OCINodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  # Subnet IDs for launching instances
  subnetIds:
    - ocid1.subnet.oc1.iad.aaaaaaaaznwweno45m7klssbzt2kyl6qa4ec34335patiolemkti6d4ioita
    - ocid1.subnet.oc1.iad.aaaaaaaau6uekgrdd446pvmqt3zfhwkpnncn2jytqwlhokurxb54mnh46tca
  
  # OCI Image ID for instances
  imageId: ocid1.image.oc1.iad.aaaaaaaaspio4cg2ttycualigcfb74yd5ixp5ovryxfjesm7y7xiayjf53dq
  
  # Default shape if not specified in NodePool
  shape: VM.Standard.E4.Flex
  
  # Tags to apply to OCI resources
  tags:
    managed-by: karpenter
    cluster: oke-cluster