apiVersion: v1
kind: Pod
metadata:
  name: test-minimal-karpenter
  namespace: default
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.9
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  nodeSelector:
    karpenter.sh/test: "true"
  tolerations:
  - key: karpenter.sh/test
    operator: Equal
    value: "true"
    effect: NoSchedule