apiVersion: v2
name: karpenter-oci
description: Karpenter with OCI provider support for Oracle Kubernetes Engine (OKE)
type: application
version: 0.1.42
appVersion: "start-io-70b03e4e"
home: https://github.com/startappdev/karpenter
sources:
  - https://github.com/startappdev/karpenter
keywords:
  - karpenter
  - oci
  - oracle
  - oke
  - autoscaling
  - kubernetes
maintainers:
  - name: StartApp Team
    email: support@startapp.com