apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "karpenter-oci.fullname" . }}-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-oci.labels" . | nindent 4 }}
data:
  settings: |
    clusterName: {{ .Values.settings.clusterName }}
    logLevel: {{ .Values.settings.logLevel }}
    batchMaxDuration: {{ .Values.settings.batchMaxDuration }}
    batchIdleDuration: {{ .Values.settings.batchIdleDuration }}
    featureGates:
      {{- range $key, $value := .Values.settings.featureGates }}
      {{ $key }}: {{ $value }}
      {{- end }}