---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: start-github-pull-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: AgBqlJmeGyS5XbIabcZZKoHozNiVmBPibWDySuHyfY/4/XFiZsYvb0HKWyQtGquFOEjajAkRDev7VVLIAqGoqTJ7TSnOFgk58T38pOgAb2ALvGiR8qg3G8ZJ5X5yLBWCIVuKxSqxrS0qNwCgcQZEznSArt+N8tubrqAbWpae4/B1Z7iKT5zO46q6QNVpxKH4K9e+3YLWgCc3l/fulD3IODKbwTWMgK9R5gkBMDVMJA6f0FoHrCG8zFW3dx/dXw/+5KRATjKa6xoH2JqZ5n5vgcOjBZJsashiMPg+Rtuzqu7v+3PQJMu6O3qvZoywfm5o1gHent5dipos71RTDC/j6JmRznjGpIhTwgU+L/U10/LPH9ipZ+tuoLjfS//k9lnzkGuYYGWW83nZEySwSU7v78GLXjFNB8KvoXOlMQU/FKUD7WEvxqiWoVLz/OI4n6AJ/E2pRsH/+An7vDqHCqRpTIG1yPA0LvSOOcc9mPvMWUeX86dIs9XPEN79szNK0LliMj0Nw5joOdxV2Qkc5tgdvTAGNKPF9uW4D8W1tFxf30X3ssHLz3XXw8G21Ixp0akMhe0zCXTkQ4pEtjVyhlDTp9PY/GVURJt3IbdtHCVf/W7G4xxGEqQqcJPZ4LKxXT06gamd1Ssj6+HIldAogCAq0G6fkhznl8MU3m+Kcr6Yfr0yy/cjMghcwFPrsd2y0RmAOPTx6jXCKOVsZf+o1NIhETpz9A9VLtYKYvrtGe1lzEpWGC/AkyaBt/OmmQEp95J5RupSCeojkQcE5QF6runtRTqDpbDjtARAyrQRvQWaKfccRuZNKwcBnztkE+ErymwiOLgE5ERtn5pfkm802hFRFJP669zT1OFxrAWLMj6AjHoz+XGdYkZAIEaHfSbunFeso+QaL/T3bsZs7U7UvNoWKH0=
  template:
    metadata:
      creationTimestamp: null
      name: start-github-pull-secret
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson