apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-oci.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-oci.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: {{ .Values.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: {{ .Values.webhook.metricsPort }}
      targetPort: webhook-metrics
      protocol: TCP
      name: webhook-metrics
  selector:
    {{- include "karpenter-oci.selectorLabels" . | nindent 4 }}